name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'web/**'

  rust:
    runs-on: ${{ matrix.os }}
    needs: changes
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Cargo fmt
        run: cargo fmt --all --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --workspace

  frontend:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            web/shared/package-lock.json
            web/overlay/package-lock.json
            web/admin/package-lock.json
      - name: Install dependencies (shared)
        working-directory: web/shared
        run: npm ci
      - name: Lint (shared)
        working-directory: web/shared
        run: npm run lint
      - name: Type check (shared)
        working-directory: web/shared
        run: npm run typecheck
      - name: Test (shared)
        working-directory: web/shared
        run: npm run test
      - name: Build (shared)
        working-directory: web/shared
        run: npm run build
      - name: Install dependencies (overlay)
        working-directory: web/overlay
        run: npm ci
      - name: Lint (overlay)
        working-directory: web/overlay
        run: npm run lint
      - name: Type check (overlay)
        working-directory: web/overlay
        run: npm run typecheck
      - name: Test (overlay)
        working-directory: web/overlay
        run: npm run test
      - name: Build (overlay)
        working-directory: web/overlay
        run: npm run build
      - name: Install dependencies (admin)
        working-directory: web/admin
        run: npm ci
      - name: Lint (admin)
        working-directory: web/admin
        run: npm run lint
      - name: Type check (admin)
        working-directory: web/admin
        run: npm run typecheck
      - name: Test (admin)
        working-directory: web/admin
        run: npm run test
      - name: Build (admin)
        working-directory: web/admin
        run: npm run build
